[package]
name = "parallel_image_crop"
version = "0.1.0"
authors = ["Jason Ramapuram <jason.ramapuram@gmail.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
image = "0.19.0"
rayon = "1.0"
itertools = "0.7.3"
libc = "0.2.42"
